service: foodfusion
image: bhavyansh001/foodfusion

servers:
  web:
    hosts:
      - 159.65.234.244
    labels:
      traefik.http.routers.foodfusion.rule: Host(`foodfusion2.diversepixel.com`)
      traefik.http.routers.foodfusion_secure.entrypoints: websecure
      traefik.http.routers.foodfusion_secure.rule: Host(`foodfusion2.diversepixel.com`)
      traefik.http.routers.foodfusion_secure.tls: true
      traefik.http.routers.foodfusion_secure.tls.certresolver: letsencrypt
  job:
    hosts:
      - 159.65.234.244
    cmd: bundle exec rake solid_queue:start

registry:
  username: bhavyansh001
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 159.65.234.244
  secret:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - REDIS_URL
    - SECRET_KEY_BASE
    - SMTP_PASSWORD

builder:
  args:
    RUBY_VERSION: 3.3.0
  remote:
    arch: amd64

accessories:
  db:
    image: postgres:16.0
    host: 159.65.234.244
    port: 5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    files:
      - config/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: 159.65.234.244
    port: 6379
    cmd: redis-server
    volumes:
      - redis-data:/data

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "hi@foodfusion.diversepixel.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web