service: foodfusion
image: bhavyansh001/foodfusion
servers:
  web:
    hosts:
      - 159.65.234.244
  job:
    hosts:
      - 159.65.234.244
    cmd: bundle exec rake solid_queue:start
registry:
  username: bhavyansh001
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 159.65.234.244
  secret:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - REDIS_URL
    - SECRET_KEY_BASE
    - SMTP_PASSWORD
builder:
  args:
    RUBY_VERSION: 3.3.0
  remote:
    arch: amd64
accessories:
  db:
    image: postgres:16.0
    host: 159.65.234.244
    port: 5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    files:
      - config/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    host: 159.65.234.244
    port: 6379
    volumes:
      - redis-data:/data
    cmd: redis-server